/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DatasourceType } from "./types/datasource-type";
import { Transformation } from "./types/transformation";
export namespace Components {
    interface NtopDatasource {
        "ds_type": DatasourceType;
    }
    interface NtopWidget {
        "height": string;
        "transformation": Transformation;
        "width": string;
    }
}
declare global {
    interface HTMLNtopDatasourceElement extends Components.NtopDatasource, HTMLStencilElement {
    }
    var HTMLNtopDatasourceElement: {
        prototype: HTMLNtopDatasourceElement;
        new (): HTMLNtopDatasourceElement;
    };
    interface HTMLNtopWidgetElement extends Components.NtopWidget, HTMLStencilElement {
    }
    var HTMLNtopWidgetElement: {
        prototype: HTMLNtopWidgetElement;
        new (): HTMLNtopWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "ntop-datasource": HTMLNtopDatasourceElement;
        "ntop-widget": HTMLNtopWidgetElement;
    }
}
declare namespace LocalJSX {
    interface NtopDatasource {
        "ds_type": DatasourceType;
    }
    interface NtopWidget {
        "height"?: string;
        "transformation": Transformation;
        "width"?: string;
    }
    interface IntrinsicElements {
        "ntop-datasource": NtopDatasource;
        "ntop-widget": NtopWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ntop-datasource": LocalJSX.NtopDatasource & JSXBase.HTMLAttributes<HTMLNtopDatasourceElement>;
            "ntop-widget": LocalJSX.NtopWidget & JSXBase.HTMLAttributes<HTMLNtopWidgetElement>;
        }
    }
}
